### ISSUE TITLE
f-string Errror

### ISSUE THREAD

**Issue by Blackmirror344** [lclassen/BdK6.5.3_P3_SoSe2021_CLASSEN_LYNN#1]
```
print(f"{pmid_data["result"][pmid]["title"]} and {pmid_data["result"][pmid]["pubdate"]}")
print("----------")
```

Du musst die Daten welche du dir über die API herunterlädst in eigenen Variablen speichern. Vorschlag:

```
title = pmid_data["result"][pmid]["title"]
date = pmid_data["result"][pmid]["pubdate"]
print(f"{name} and {date}")
```

**Comment by lclassen** [comment]
Die Änderung wurde übernommen, nur in der Zeile
_print(f"{name} and {date}")_
wurde name durch die richtige Variable title ersetzt.
